spring:
  application:
    name: BookShelf
  datasource:
    url: jdbc:mysql://localhost:3306/book_shelf
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 2MB